return {
  { "akinsho/bufferline.nvim", enabled = false },
  { "nvim-lualine/lualine.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "folke/which-key.nvim", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "lewis6991/gitsigns.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "folke/ts-comments.nvim", enabled = false },
  { "MagicDuck/grug-far.nvim", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "mfussenegger/nvim-lint", enabled = false },
  { "nvim-treesitter/nvim-treesitter-textobjects", enabled = false },
  { "nvim-mini/mini.ai", enabled = false },
  { "nvim-mini/mini.icons", enabled = false },
  { "nvim-mini/mini.pairs", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "catppuccin/nvim", enabled = false },
}
